[webserver]
43.204.238.50 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/Mumbai_server_key.pem

[dbserver]
13.235.75.175 ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/Mumbai_server_key.pem